CREATE DATABASE IF NOT EXISTS PASTELERIA;
USE PASTELERIA;

-- ============================
-- TABLA EMPLEADO
-- ============================
CREATE TABLE EMPLEADO (
    ID_EMPLEADO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(45) NOT NULL,
    APELLIDOS VARCHAR(70) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    ROL VARCHAR(20) NOT NULL,
    CONTRASEÑA VARCHAR(100) NOT NULL,
    CONSTRAINT PK_EMPLEADO PRIMARY KEY (ID_EMPLEADO)
);

-- ============================
-- TABLA CLIENTE
-- ============================
CREATE TABLE CLIENTE (
    ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(45) NOT NULL, 
    APELLIDOS VARCHAR(80) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    CONTRASEÑA VARCHAR (100) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

-- ============================
-- TABLA REGISTRO HORARIO
-- ============================
CREATE TABLE REGISTRO (
    ID_REGISTRO INT NOT NULL AUTO_INCREMENT,
    FECHA DATE NOT NULL,
    HORA_ENTRADA TIME NOT NULL,
    HORA_SALIDA TIME NOT NULL,
    HORAS_TRABAJADAS DECIMAL(4, 2),
    EMPLEADO_ID_EMPLEADO INT NOT NULL,
    CONSTRAINT PK_REGISTRO PRIMARY KEY (ID_REGISTRO),
    CONSTRAINT FK_REGISTRO_EMPLEADO FOREIGN KEY (EMPLEADO_ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO)
);

-- ============================
-- TABLA PEDIDO
-- ============================
CREATE TABLE PEDIDO (
    ID_PEDIDO INT NOT NULL AUTO_INCREMENT,
    FECHA_PEDIDO DATETIME NOT NULL,
    FECHA_RECOGIDA DATETIME NOT NULL,
    ESTADO VARCHAR(15) NOT NULL,
    PRECIO_TOTAL DECIMAL(10, 2) NOT NULL,
    OBSERVACIONES VARCHAR(250),
    CLIENTE_ID_CLIENTE INT NOT NULL,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (CLIENTE_ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

-- ============================
-- TABLA PRODUCTO (CORREGIDA)
-- ============================
DROP TABLE IF EXISTS PRODUCTO;

CREATE TABLE PRODUCTO (
    ID_PRODUCTO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(60) NOT NULL,
    DESCRIPCION VARCHAR(250) NOT NULL,
    PRECIO DECIMAL(10, 2) NOT NULL,
    RECETA VARCHAR(200) NOT NULL,
    STOCK INT NOT NULL DEFAULT 0,
    TIPO_PRODUCTO VARCHAR(200) NOT NULL,
    IMAGEN VARCHAR(300) NULL,
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO)
);

-- ============================
-- TABLA DETALLE_PEDIDO
-- ============================
CREATE TABLE DETALLE_PEDIDO (
    ID_DETALLE_PEDIDO INT NOT NULL AUTO_INCREMENT,
    PRODUCTO_CANTIDAD INT NOT NULL,
    PEDIDO_UNITARIO DECIMAL(10, 2) NOT NULL,
    SUBTOTAL DECIMAL(10, 2) NOT NULL,
    PEDIDO_ID_PEDIDO INT NOT NULL,
    PRODUCTO_ID_PRODUCTO INT NOT NULL,
    CONSTRAINT PK_DETALLE_PEDIDO PRIMARY KEY (ID_DETALLE_PEDIDO),
    CONSTRAINT FK_DETALLE_PEDIDO_PEDIDO FOREIGN KEY (PEDIDO_ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO),
    CONSTRAINT FK_DETALLE_PEDIDO_PRODUCTO FOREIGN KEY (PRODUCTO_ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
);

-- ============================
-- TABLA PROVEEDOR
-- ============================
CREATE TABLE PROVEEDOR (
    ID_PROVEEDOR INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL, 
    EMAIL VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    DIRECCION VARCHAR(80) NOT NULL,
    CONSTRAINT PK_PROVEEDOR PRIMARY KEY (ID_PROVEEDOR)
);

-- ============================
-- TABLA INGREDIENTE
-- ============================
CREATE TABLE INGREDIENTE (
    ID_INGREDIENTE INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    CANTIDAD INT NOT NULL,
    PROVEEDOR_ID_PROVEEDOR INT NOT NULL,
    CONSTRAINT PK_INGREDIENTE PRIMARY KEY (ID_INGREDIENTE),
    CONSTRAINT FK_INGREDIENTE_PROVEEDOR FOREIGN KEY (PROVEEDOR_ID_PROVEEDOR) REFERENCES PROVEEDOR (ID_PROVEEDOR)
);

-- ============================
-- TABLA PRODUCTO_has_INGREDIENTE
-- ============================
CREATE TABLE PRODUCTO_has_INGREDIENTE (
    PRODUCTO_ID_PRODUCTO INT NOT NULL,
    INGREDIENTE_ID_INGREDIENTE INT NOT NULL,
    CONSTRAINT PK_PRODUCTO_has_INGREDIENTE PRIMARY KEY (PRODUCTO_ID_PRODUCTO, INGREDIENTE_ID_INGREDIENTE),
    CONSTRAINT FK_PRODUCTO_has_INGREDIENTE_PRODUCTO FOREIGN KEY (PRODUCTO_ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
    CONSTRAINT FK_PRODUCTO_has_INGREDIENTE_INGREDIENTE FOREIGN KEY (INGREDIENTE_ID_INGREDIENTE) REFERENCES INGREDIENTE (ID_INGREDIENTE)
);
