DROP DATABASE IF EXISTS PASTELERIA;
CREATE DATABASE IF NOT EXISTS PASTELERIA;
USE PASTELERIA;

-- ============================
-- TABLA USUARIO
-- ============================
CREATE TABLE USUARIO (
    ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    ROL VARCHAR(20) NOT NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID)
);

-- ============================
-- TABLA REGISTRO HORARIO
-- ============================
CREATE TABLE REGISTRO (
    ID_REGISTRO INT NOT NULL AUTO_INCREMENT,
    FECHA DATE NOT NULL,
    HORA_ENTRADA TIME NOT NULL,
    HORA_SALIDA TIME NOT NULL,
    HORAS_TRABAJADAS DECIMAL(4, 2),
    USUARIO_ID INT NOT NULL,
    CONSTRAINT PK_REGISTRO PRIMARY KEY (ID_REGISTRO),
    CONSTRAINT FK_REGISTRO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
);

-- ============================
-- TABLA PRODUCTO
-- ============================
CREATE TABLE PRODUCTO (
    ID_PRODUCTO INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(60) NOT NULL,
    DESCRIPCION VARCHAR(250) NOT NULL,
    PRECIO DECIMAL(10, 2) NOT NULL,
    RECETA VARCHAR(200) NOT NULL,
    STOCK INT NOT NULL DEFAULT 0,
    TIPO_PRODUCTO VARCHAR(200) NOT NULL,
    IMAGEN VARCHAR(300),
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO)
);

-- ============================
-- TABLA INGREDIENTE
-- ============================
CREATE TABLE INGREDIENTE (
    ID_INGREDIENTE INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    CANTIDAD INT NOT NULL,
    PROVEEDOR VARCHAR(50) NOT NULL,
    CONSTRAINT PK_INGREDIENTE PRIMARY KEY (ID_INGREDIENTE)
);

-- ============================
-- TABLA PRODUCTO_has_INGREDIENTE
-- ============================
CREATE TABLE PRODUCTO_has_INGREDIENTE (
    PRODUCTO_ID_PRODUCTO INT NOT NULL,
    INGREDIENTE_ID_INGREDIENTE INT NOT NULL,
    CONSTRAINT PK_PRODUCTO_has_INGREDIENTE PRIMARY KEY (PRODUCTO_ID_PRODUCTO, INGREDIENTE_ID_INGREDIENTE),
    CONSTRAINT FK_PRODUCTO_has_INGREDIENTE_PRODUCTO FOREIGN KEY (PRODUCTO_ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
    CONSTRAINT FK_PRODUCTO_has_INGREDIENTE_INGREDIENTE FOREIGN KEY (INGREDIENTE_ID_INGREDIENTE) REFERENCES INGREDIENTE (ID_INGREDIENTE)
);

-- ============================
-- TABLA PEDIDO (CORREGIDA)
-- ============================
CREATE TABLE PEDIDO (
    ID INT NOT NULL AUTO_INCREMENT,
    FECHA VARCHAR(255) NOT NULL,
    RECOGER VARCHAR(255) NOT NULL,
    TOTAL DOUBLE NOT NULL,
    ESTADO VARCHAR(50) NOT NULL DEFAULT 'Pendiente',
    USUARIO_ID INT NOT NULL,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID),
    CONSTRAINT FK_PEDIDO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
);

-- ============================
-- TABLA PEDIDO_PRODUCTO
-- ============================
CREATE TABLE PEDIDO_PRODUCTO (
    ID INT NOT NULL AUTO_INCREMENT,
    PRODUCTO_ID INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    IMAGEN VARCHAR(255),
    PRECIO DOUBLE NOT NULL,
    CANTIDAD INT NOT NULL,
    PEDIDO_ID INT NOT NULL,
    CONSTRAINT PK_PEDIDO_PRODUCTO PRIMARY KEY (ID),
    CONSTRAINT FK_PEDIDO_PRODUCTO_PEDIDO FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID)
);

CREATE TABLE BENEFICIOS (
	ID_BENEFICIOS INT NOT NULL AUTO_INCREMENT,
    FECHA DATE NOT NULL,
    GANANCIA DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_BENEFICIOS PRIMARY KEY (ID_BENEFICIOS)
);

-- ============================
-- TABLA MENSAJE
-- ============================
CREATE TABLE mensaje (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255),
    email VARCHAR(255),
    telefono VARCHAR(255),
    mensaje TEXT,
    fecha VARCHAR(255),
    leido BOOLEAN
);
ALTER TABLE REGISTRO MODIFY HORA_SALIDA TIME NULL;
